# Generated by Django 2.1.7 on 2019-04-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20190206_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.IntegerField(null=True),
        ),
    ]
