# Generated by Django 2.1.7 on 2019-04-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_auto_20190405_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.IntegerField(max_length=9),
        ),
    ]
