# Generated by Django 2.1.7 on 2019-04-05 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_auto_20190405_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')]),
        ),
    ]
