# Generated by Django 2.1.7 on 2019-04-05 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_auto_20190405_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
