# Generated by Django 2.1.7 on 2019-04-16 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_auto_20190405_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passengers',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
