# Generated by Django 2.1.7 on 2019-04-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_auto_20190416_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passengers',
        ),
        migrations.AddField(
            model_name='passenger',
            name='passengers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='details.Ticket'),
        ),
    ]
