# Generated by Django 2.1.7 on 2019-04-16 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_auto_20190416_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='number_of_passengers',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
