# Generated by Django 2.1.7 on 2019-04-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0014_passenger_number_of_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='passengers',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
