# Generated by Django 2.1.7 on 2019-04-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_auto_20190417_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number_of_tickets',
            field=models.PositiveIntegerField(choices=[(1, 'a'), (2, 'm')], default=1),
        ),
    ]
