# Generated by Django 2.1.7 on 2019-04-17 18:26

import details.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_ticket_number_of_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1, verbose_name=details.models.Ticket)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_of_tickets',
        ),
    ]
