# Generated by Django 2.1.7 on 2019-04-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0017_auto_20190417_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='number_of_tickets',
        ),
        migrations.AddField(
            model_name='passenger',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketsn', to='details.Ticket'),
        ),
    ]
