# Generated by Django 2.1.7 on 2019-04-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0020_auto_20190417_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='number_of_tickets',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1),
        ),
    ]
