# Generated by Django 2.2 on 2019-04-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0021_auto_20190417_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='number_of_tickets',
            new_name='tickets_number',
        ),
    ]
