# Generated by Django 2.1.7 on 2019-06-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0022_auto_20190418_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
