# Generated by Django 2.1.7 on 2019-06-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0024_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
