# Generated by Django 2.1.7 on 2019-06-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0026_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
